blog/urls.py
from django.urls import path
from blog import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<slug:post>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('post/<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

juvas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status=Post.Status.PUBLISHED)
    

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'draft'
        PUBLISHED = 'published'

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    feature_image = models.ImageField(upload_to="uploads/", null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=Status, default='draft')
    
    objects = models.Manager()
    published = PublishedManager()
    
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.slug)])
    
    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'content']

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404

from blog.forms import EmailPostForm, CommentForm
from blog.models import Post

from taggit.models import Tag

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    template_name = 'blog/post/list.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_slug = self.kwargs.get('tag_slug')
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[tag])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.kwargs.get('tag_slug')
        return context
    
    
    
class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post/detail.html'
    
    def get_object(self, queryset=None):
        post = self.kwargs.get('post')
        return get_object_or_404(Post, slug=post)
    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['post'] = self.object
        context['comments'] = self.object.comments.filter(active=True)
        context['comment_form'] = CommentForm()
        return context
    

def post_share(request, post_id, *args, **kwargs):
    post = get_object_or_404(Post, id=kwargs.get('post_id'), status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, form_email=None, recipient_list=[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

    
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return HttpResponseRedirect(reverse('blog:post_detail', args=[post.slug]))

blog/templates/_pagination.html
<div class="pagination">
  <div id="pagination-container">
    <div id="indicator"></div>
    {% if page_obj.has_previous %}
      <a class="pag-link" href="?page={{ page_obj.previous_page_number }}">Prev</a>

      {% if page_obj.number > 3 %}
        <a class="pag-link" href="?page=1">1</a>
        {% if page_obj.number > 4 %}
          <a class="pag-link">...</a>
        {% endif %}
      {% endif %}
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="pag-link" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="pag-link" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
        <a class="pag-link">...</a>
        <a class="pag-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
      {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
        <a class="pag-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
      {% endif %}

      <a class="pag-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  </div>
</div>

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      JUVAS -{% block title %}

      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    {% include 'blog/navigation.html' %}

    <main>
      {% block content %}

      {% endblock %}
    </main>



    
    <aside>
      <h2>Sidebar</h2>

      {% for post in similar_posts %}
        <p class="">
          <a href="{{ post.get_absolute_url }}" class="">{{ post.title }}</a>
        </p>
      {% empty %}
        <p class="">There are no similar posts.</p>
      {% endfor %}

      <p class="">
        Posts{% total_posts %}
      </p>

      <div class="">
        {% show_latest_posts %}
      </div>

      <div class="">
        <h3 class="">most commented posts</h3>
        <ul class="">
          {% for post in most_commented_posts %}
            <a href="{{ post.get_absolute_url }}" class="">{{ post.title }}</a>
          {% endfor %}
        </ul>
      </div>
      <div class="">
        <a href="{% url 'blog:post_feed' %}" class="">Subsribe to rss</a>
      </div>
    </aside>

    <footer>
      <p>&copy; 2023 My Blog. All rights reserved.</p>
    </footer>

    <script src="{% static 'js/navbar.js' %}"></script>
  </body>
</html>

blog/templates/blog/navigation.html
{% load static %}

<nav class="navbar">
  <span class="navbar-toggle" id="js-navbar-toggle"><i class="fas fas-bars"></i></span>
  <a href="/"><img src="{% static 'images/juvas.png' %}" alt="Logo" /></a>
  <ul class="main-nav" id="js-menu">
    <li>
      <a href="/" class="nav-links">Home</a>
    </li>
    <li>
      <a href="/products" class="nav-links">About</a>
    </li>

    <li>
      <a href="/contact" class="nav-links">Contact</a>
    </li>
    <li>
      <a href="/blog" class="nav-links">Blog</a>
    </li>
  </ul>
</nav>

blog/templates/blog/post/detail.html
{% block content %}
  <h1>{{ post.title }}</h1>
  <p>By {{ post.author }} on {{ post.published_date }}</p>
  <div>{{ post.content|safe }}</div>
  <a href="{% url 'blog:post_list' %}">Back to Blog</a>
  <hr />
  <p class="">
    <a href="{% url 'blog:post_share' post.id %}" class="">Share this post</a>
  </p>
  <h2>Comments</h2>
  {% with total_comments=comment.count %}
    <h2>Total comments is {{ total_comments|pluralize }}</h2>
  {% endwith %}
  <ul>
    {% for comment in comments %}
      <li>Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
        said: {{ comment.content|linebreaks }}</li>
    {% empty %}
      <li>No comments yet.</li>
    {% endfor %}
  </ul>

  <h2>Leave a comment</h2>
  <form method="post" action="{% url 'blog:post_comment' post.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<h1>Latest Blog Posts</h1>
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
      <small>Published on {{ post.published_date }}</small>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}
  Blog Posts
{% endblock %}

{% block content %}
  <header class="header">
    <h1 class="">Blog Posts</h1>
  </header>

  {% if tag %}
    <h2>Posts tagged with "{{ tag }}"</h2>
  {% endif %}

  {% for post in posts %}
    <section class="{% if forloop.counter|divisibleby:2 %}
        
        
        
        
         blog-card alt




      {% else %}
        
        
        
        
         blog-card




      {% endif %}">
      <div class="meta">
        {% if post.feature_image %}
          <div class="photo" >
            <img src="{{ post.feature_image.url }}" alt="" class="" style="background-size: cover; background-position: center; max-width: 100%; max-height: 100%;">
          </div>
        {% endif %}
        <ul class="details">
          <li class="author">
            <a href="" class="">{{ post.author }}</a>
          </li>
          <li class="date">{{ post.publish }}</li>
          <div class="tags">
            <ul>
              {% for tag in post.tags.all %}
                <li>
                  <a href="{% url 'blog:post_list' tag.slug %}" class="">{{ tag.name }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </ul>
      </div>

      <div class="description">
        <h1><a href="{{ post.get_absolute_url }}" class=""></a>{{ post.title }}</h1>
        <h2>{{ post.overview }}</h2>
        <p>{{ post.content|truncatewords:30|linebreaks }}</p>
        <p class="read-more">
          <a href="{{ post.get_absolute_url }}" class="">Read More</a>
        </p>
      </div>
    </section>
  {% endfor %}
  {% include '_pagination.html' with page=page_obj %}
{% endblock %}

blog/templates/blog/share.html
{% extends 'blog/base.html' %}

<div class="share-container">
  {% if sent %}
    <h1 class="">Email sent successfully</h1>
    <p class="">{{ post.title }} has been shared with {{ form.cleaned_data.to }}.</p>
    {% ele %}
    <h1>Share this Post</h1>

    <form action="{% url 'share_post' post.id %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Your Name:</label>
        <input type="text" id="name" name="name" required />
      </div>
      <div class="form-group">
        <label for="email">Your Email:</label>
        <input type="email" id="email" name="email" required />
      </div>
      <div class="form-group">
        <label for="to">Recipient's Email:</label>
        <input type="email" id="to" name="to" required />
      </div>
      <div class="form-group">
        <label for="comments">Comments:</label>
        <textarea id="comments" name="comments" rows="4"></textarea>
      </div>
      <button type="submit">Share</button>
    </form>
  {% endif %}
</div>

templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      JUVAS -{% block title %}

      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <header>
      <h1>Welcome to My Blog</h1>
      <nav>
        <ul>
          {% comment %} <li>
            <a href="{% url 'home' %}">Home</a>
          </li> {% endcomment %}
          {% comment %} <li>
            <a href="{% url 'about' %}">About</a>
          </li> {% endcomment %}
          {% comment %} <li>
            <a href="{% url 'contact' %}">Contact</a>
          </li> {% endcomment %}
        </ul>
      </nav>
    </header>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <aside>
      <h2>Sidebar</h2>

      {% for post in similar_posts %}
        <p class="">
          <a href="{{ post.get_absolute_url }}" class="">{{ post.title }}</a>
        </p>
      {% empty %}
        <p class="">There are no similar posts.</p>
      {% endfor %}

      <p class="">
        Posts{% total_posts %}
      </p>

      <div class="">
        {% show_latest_posts %}
      </div>

      <div class="">
        <h3 class="">most commented posts</h3>
        <ul class="">
          {% for post in most_commented_posts %}
            <a href="{{ post.get_absolute_url }}" class="">{{ post.title }}</a>
          {% endfor %}
        </ul>
      </div>
      <div class="">
        <a href="{% url 'blog:post_feed' %}" class="">Subsribe to rss</a>
      </div>
    </aside>

    <footer>
      <p>&copy; 2023 My Blog. All rights reserved.</p>
    </footer>
  </body>
</html>